"""
pdf_export.py
=============
PDF report generation — zero Streamlit dependency.

Responsibilities:
- Sanitize text for latin-1 font encoding
- Render the structured AI report as a downloadable PDF
"""

from fpdf import FPDF


def sanitize(text) -> str:
    """
    Replace non-latin-1 characters with safe ASCII equivalents.
    Helvetica (the default fpdf2 font) only supports latin-1.
    """
    if not isinstance(text, str):
        text = str(text)
    return (
        text
        .replace('\u2014', '--').replace('\u2013', '-')   # em/en dash
        .replace('\u2018', "'").replace('\u2019', "'")    # smart single quotes
        .replace('\u201c', '"').replace('\u201d', '"')    # smart double quotes
        .replace('\u2022', '-').replace('\u2026', '...')  # bullet, ellipsis
        .replace('\u00ae', '(R)').replace('\u2122', '(TM)')
        .replace('\u00b0', ' deg').replace('\u00b1', '+/-')
        .replace('\u2012', '-').replace('\u2015', '--')
        .encode('latin-1', errors='replace').decode('latin-1')
    )


class _ReportPDF(FPDF):
    def header(self):
        self.set_fill_color(30, 30, 50)
        self.rect(0, 0, 210, 25, 'F')
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(169, 164, 255)
        self.cell(0, 15, "AI Heart Risk Health Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(180, 180, 180)
        self.set_font("Helvetica", size=9)
        self.cell(
            0, 8,
            "Generated by Heart Risk Predictor - For informational purposes only",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def section_title(self, title: str, color=(108, 99, 255)):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*color)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*color)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def body_text(self, text: str):
        self.set_font("Helvetica", size=10)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 6, sanitize(text), new_x="LMARGIN", new_y="NEXT")


def generate_pdf(
    report: dict,
    patient_data: dict,
    risk_level: str,
    risk_score: float,
) -> bytes:
    """Render the AI report dict as a PDF and return raw bytes."""
    pdf = _ReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    risk_color = (231, 76, 60) if risk_level == "HIGH" else (39, 174, 96)

    # ── Patient Metrics ───────────────────────────────────────────────────────
    pdf.section_title("Your Metrics")
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(50, 50, 50)

    metrics = [
        ("Age",            str(patient_data.get("age", "N/A"))),
        ("Sex",            str(patient_data.get("sex", "N/A"))),
        ("Risk Level",     risk_level),
        ("Risk Score",     f"{risk_score:.1f}%"),
        ("Cholesterol",    f"{patient_data.get('chol', 'N/A')} mg/dl"),
        ("Blood Pressure", f"{patient_data.get('trestbps', 'N/A')} mmHg"),
        ("Max Heart Rate", f"{patient_data.get('thalach', 'N/A')} bpm"),
        ("ST Depression",  str(patient_data.get("oldpeak", "N/A"))),
    ]
    col_w = 45
    val_w = 50
    for i, (label, value) in enumerate(metrics):
        # Start a new row for every pair
        if i % 2 == 0:
            x_start = pdf.get_x()
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(col_w, 7, f"{label}:")
        pdf.set_font("Helvetica", size=10)
        pdf.set_text_color(*risk_color if label == "Risk Level" else (30, 30, 30))
        pdf.cell(val_w, 7, sanitize(value))
        if i % 2 == 1 or i == len(metrics) - 1:
            pdf.ln(7)
    pdf.ln(4)

    # ── Risk Summary ──────────────────────────────────────────────────────────
    pdf.section_title("Your Risk Summary")
    pdf.body_text(report.get("risk_summary", ""))
    pdf.ln(4)

    # ── Contributing Factors ──────────────────────────────────────────────────
    pdf.section_title("Your Contributing Factors")
    pdf.set_font("Helvetica", size=10)
    for factor in report.get("contributing_factors", []):
        pdf.set_text_color(231, 76, 60)
        pdf.cell(11, 6, "  *")
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 6, sanitize(factor), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Recommendations ───────────────────────────────────────────────────────
    pdf.section_title("Personalized Recommendations for You")
    for rec in report.get("recommendations", []):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(108, 99, 255)
        pdf.cell(0, 6, sanitize(rec.get("title", "")), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", size=10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, sanitize(rec.get("detail", "")), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
    pdf.ln(2)

    # ── Sources ───────────────────────────────────────────────────────────────
    pdf.section_title("Sources")
    pdf.set_font("Helvetica", size=10)
    for src in report.get("sources", []):
        pdf.set_text_color(55, 138, 221)
        pdf.cell(6, 6, "*")
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 6, sanitize(src), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    pdf.section_title("Disclaimer", color=(200, 80, 120))
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(
        0, 5,
        "This AI-generated report is for educational and informational purposes only. "
        "It does not constitute medical advice, clinical diagnosis, or treatment recommendations. "
        "All outputs are generated by a machine learning model and a large language model and may contain errors. "
        "Always consult a qualified healthcare professional before making any health-related decisions.",
        new_x="LMARGIN", new_y="NEXT",
    )

    return bytes(pdf.output())
